<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Libs\*.dll">
            <HintPath>Libs\%(FileName).dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="DecompiledCode\**\*.cs" />
        <None Include="DecompiledCode\**\*.cs" />
    </ItemGroup>

</Project>